//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.28 at 06:24:06 PM IST 
//


package com.mitester.jaxbparser.validation;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for nameEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="nameEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
 *     &lt;enumeration value="req"/>
 *     &lt;enumeration value="res"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "nameEnumType")
@XmlEnum
public enum NameEnumType {

    @XmlEnumValue("req")
    REQ("req"),
    @XmlEnumValue("res")
    RES("res");
    private final String value;

    NameEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NameEnumType fromValue(String v) {
        for (NameEnumType c: NameEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
