//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.16 at 06:32:49 AM EDT 
//


package com.mitester.jaxbparser.server;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ACTION }
     * 
     */
    public ACTION createACTION() {
        return new ACTION();
    }

    /**
     * Create an instance of {@link Fline }
     * 
     */
    public Fline createFline() {
        return new Fline();
    }

    /**
     * Create an instance of {@link OTHERSBODY }
     * 
     */
    public OTHERSBODY createOTHERSBODY() {
        return new OTHERSBODY();
    }

    /**
     * Create an instance of {@link SIPTORTURE }
     * 
     */
    public SIPTORTURE createSIPTORTURE() {
        return new SIPTORTURE();
    }

    /**
     * Create an instance of {@link Sdp }
     * 
     */
    public Sdp createSdp() {
        return new Sdp();
    }

    /**
     * Create an instance of {@link HEADERS }
     * 
     */
    public HEADERS createHEADERS() {
        return new HEADERS();
    }

    /**
     * Create an instance of {@link EMPTYMSG }
     * 
     */
    public EMPTYMSG createEMPTYMSG() {
        return new EMPTYMSG();
    }

    /**
     * Create an instance of {@link TEST }
     * 
     */
    public TEST createTEST() {
        return new TEST();
    }

    /**
     * Create an instance of {@link DELMSG }
     * 
     */
    public DELMSG createDELMSG() {
        return new DELMSG();
    }

    /**
     * Create an instance of {@link TESTFLOW }
     * 
     */
    public TESTFLOW createTESTFLOW() {
        return new TESTFLOW();
    }

    /**
     * Create an instance of {@link CONTENT }
     * 
     */
    public CONTENT createCONTENT() {
        return new CONTENT();
    }

    /**
     * Create an instance of {@link StatusLine }
     * 
     */
    public StatusLine createStatusLine() {
        return new StatusLine();
    }

    /**
     * Create an instance of {@link XMLBODY }
     * 
     */
    public XMLBODY createXMLBODY() {
        return new XMLBODY();
    }

    /**
     * Create an instance of {@link WAIT }
     * 
     */
    public WAIT createWAIT() {
        return new WAIT();
    }

    /**
     * Create an instance of {@link DELLF }
     * 
     */
    public DELLF createDELLF() {
        return new DELLF();
    }

    /**
     * Create an instance of {@link DELCR }
     * 
     */
    public DELCR createDELCR() {
        return new DELCR();
    }

    /**
     * Create an instance of {@link ADDCRCR }
     * 
     */
    public ADDCRCR createADDCRCR() {
        return new ADDCRCR();
    }

    /**
     * Create an instance of {@link ORDERAS }
     * 
     */
    public ORDERAS createORDERAS() {
        return new ORDERAS();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link LINE }
     * 
     */
    public LINE createLINE() {
        return new LINE();
    }

    /**
     * Create an instance of {@link ADDCRLF }
     * 
     */
    public ADDCRLF createADDCRLF() {
        return new ADDCRLF();
    }

    /**
     * Create an instance of {@link ReqLine }
     * 
     */
    public ReqLine createReqLine() {
        return new ReqLine();
    }

    /**
     * Create an instance of {@link TXTBODY }
     * 
     */
    public TXTBODY createTXTBODY() {
        return new TXTBODY();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link SDPBODY }
     * 
     */
    public SDPBODY createSDPBODY() {
        return new SDPBODY();
    }

    /**
     * Create an instance of {@link ADDLFLF }
     * 
     */
    public ADDLFLF createADDLFLF() {
        return new ADDLFLF();
    }

    /**
     * Create an instance of {@link File }
     * 
     */
    public File createFile() {
        return new File();
    }

    /**
     * Create an instance of {@link MEDIA }
     * 
     */
    public MEDIA createMEDIA() {
        return new MEDIA();
    }

    /**
     * Create an instance of {@link DELCRLF }
     * 
     */
    public DELCRLF createDELCRLF() {
        return new DELCRLF();
    }

    /**
     * Create an instance of {@link DUPMSG }
     * 
     */
    public DUPMSG createDUPMSG() {
        return new DUPMSG();
    }

    /**
     * Create an instance of {@link ADDMSG }
     * 
     */
    public ADDMSG createADDMSG() {
        return new ADDMSG();
    }

    /**
     * Create an instance of {@link APPEND }
     * 
     */
    public APPEND createAPPEND() {
        return new APPEND();
    }

}
