//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.01 at 04:25:59 PM IST 
//


package com.mitester.jaxbparser.server;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for recvEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="recvEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
 *     &lt;enumeration value="req"/>
 *     &lt;enumeration value="res"/>
 *     &lt;enumeration value="media"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "recvEnumType")
@XmlEnum
public enum RecvEnumType {

    @XmlEnumValue("req")
    REQ("req"),
    @XmlEnumValue("res")
    RES("res"),
    @XmlEnumValue("media")
    MEDIA("media");
    private final String value;

    RecvEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RecvEnumType fromValue(String v) {
        for (RecvEnumType c: RecvEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
